# Generated by Django 5.1.2 on 2024-10-18 15:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
        ('users', '0002_alter_buyeruser_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('total', models.IntegerField()),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('dateOrder', models.DateTimeField(auto_now=True)),
                ('completionDate', models.DateTimeField()),
                ('shipping', models.IntegerField(choices=[('Envio por Correios', 'Envio por Correios'), ('Retirada', 'Retirada')])),
                ('status', models.IntegerField(choices=[('Pending', 'Pending'), ('Preparing', 'Preparing'), ('Delivered', 'Delivered'), ('Canceled', 'Canceled'), ('Finished', 'Finished')])),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='buyer_user', to='users.buyeruser')),
                ('shoppinglist', models.ManyToManyField(max_length=200, related_name='orderlist', to='orders.orderitem')),
            ],
        ),
    ]
