# Generated by Django 5.1.2 on 2024-10-18 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='total',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
