# Generated by Django 5.1.2 on 2024-10-18 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_alter_order_shipping_alter_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='completionDate',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
