# Generated by Django 5.1.2 on 2024-10-22 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_remove_orderitem_total'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='dateOrder',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
