# Generated by Django 5.1.2 on 2024-10-17 19:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='buyeruser',
            options={},
        ),
        migrations.RemoveField(
            model_name='buyeruser',
            name='supplieruser_ptr',
        ),
        migrations.AlterField(
            model_name='buyeruser',
            name='adress',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='buyer_adr', to='users.adressuser'),
        ),
        migrations.AlterField(
            model_name='buyeruser',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='buyer_user', serialize=False, to=settings.AUTH_USER_MODEL),
        ),
    ]
